<%@ page contentType="text/html; charset=UTF-8" language="java" %>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Simple JSP Example</title>
</head>
<body>
    <h1>Welcome to the Simple JSP Example</h1>
    <p>This is a simple web page where the content is dynamically generated by JSP.</p>
    <p>Current Date and Time: <%= new java.util.Date() %></p>
</body>
</html>
